CREATE TABLE email_verification (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  verification_code VARCHAR(64) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
)
ENGINE=InnoDB;
