name: Run the flyway container migrations
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/flyway_run_container_migration.yml
jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Command in Docker Container
        uses: addnab/docker-run-action@v3
        with:
          run: |
            flyway info
            flyway repair
            flyway migrate
            flyway info
          image: ghcr.io/websoftwares/textmod/flyway/4a5b802d3b9da926e4a65e3e31611fb296a0e55c:latest
          options: -e FLYWAY_MIXED=true -e FLYWAY_EDITION=community -e FLYWAY_URL=jdbc:mysql://textmod-mysql-server.mysql.database.azure.com:3306?useUnicode=true&characterEncoding=UTF-8&useSSL=true -e FLYWAY_SCHEMAS=textmod -e FLYWAY_USER=textmod_admin@textmod-mysql-server -e  FLYWAY_PASSWORD=${{ secrets.mysql_admin_password }}
